# Image Store Settings
PHOTOS_UPLOAD_TO = 'photos/'
PHOTOS_IMAGES_ON_PAGE = 20
PHOTOS_SELF_MANAGE = True
PHOTOS_TEMPLATE = 'base.html'
PHOTOS_SHOW_USER = True
PHOTOS_LOAD_CSS = True
# 2.5MB
PHOTOS_MAX_UPLOAD_SIZE = "2621440"
