from django.conf.urls import include, patterns, url


urlpatterns = patterns('accounts.views',
    url(r'^signin/$',
       'signin',
       name='signin'),
    url(r'^loginredirect/$',
        'loginredirect',
        name='loginredirect'),
    url(r'^redirect/(?P<username>[-\w]+)/$',
        'loginredirect',
        name='redirectToProfile'),
    url(r'^redirect/(?P<username>[-\w]+)/(?P<tab>[-\w]+)$',
        'loginredirect',
        name='redirectToProfile'),
    url(r'^(?P<username>[-\w]+)/signup/complete/$',
       'loginredirect',
       name='userena_signup_complete'),
   url(r'^signup/$',
       'signup',
       {'template_name': 'accounts/signup/form.html'},
       name='signup'),
    url(r'^signup/email/$',
        'signup_email',
        name='signup_email'),
    # url is hard coded in getProfileDetails() in accounts.pipeline.py
    url(r'^signup/social/$',
        'signupSocial',
        name='signupSocial'),
    url(r'^claim-profile/(?P<username>[-\w]+)$',
        'claim_profile',
        name='claim_profile'),
    url(r'^claim-profile-verify/(?P<username>[-\w]+)$',
        'claim_profile_verify',
        name='claim_profile_verify'),
    url(r'^claim-profile-verify/(?P<username>[-\w]+)/(?P<error>[-\w]+)$',
        'claim_profile_verify',
        name='claim_profile_error'),
)
