from django.conf.urls import include, patterns, url


view_location = 'customProfile.views'
urlpatterns = patterns(view_location,
    # News Tab
    url(r'^$',
        'profileRedirect',
        {'redirect_url': 'musician:news'},
        name='home'),
    url(r'^news/$',
        'artist_news',
        name='news'),
    # About Tab
    url(r'^about/', include(patterns(view_location,
        url(r'^links/edit/$',
            'artist_social_links',
            name='socialLinksForm'),
    ))),
    # Shows Tab
    url(r'^shows/', include(patterns(view_location,
        url(r'^$',
            'shows',
            name='shows'),
        url(r'^(?P<year>\d{4})/$',
            'shows',
            name='shows'),
    ))),
    # Photos
    url(r'^photos/', include(patterns(view_location,
        url(r'^$',
            'artist_photos',
            name='photos'),
        url(r'^links/edit/$',
            'artist_photo_links',
            name='photoLinksForm'),
    ))),
    # Music Tab
    url(r'^music/', include(patterns(view_location,
        url(r'^links/edit/$',
            'music_links',
            name='musicLinksForm'),
    ))),
    # Video Tab
    url(r'^videos/', include(patterns(view_location,
        url(r'^links/edit/$',
            'artist_video_links',
            name='videoLinksForm'),
    ))),
)

view_location = 'customProfile.musician.views'
urlpatterns += patterns(view_location,
    # About Tab
    url(r'^about/', include(patterns(view_location,
        url(r'^$',
            'about',
            name='about'),
        # Forms
        url(r'^biography/edit/$',
            'biography',
            name='biographyForm'),
        url(r'^contact/edit/$',
            'contact_info',
            name='userContactForm'),
        url(r'^member/add/$',
            'members',
            name='memberForm'),
        url(r'^member/edit/(?P<memberID>[\.\w-]+)$',
            'members',
            name='memberForm'),
        url(r'^(?P<contactType>[\.\w-]+)/edit/$',
            'contacts',
            name='contactForm'),
    ))),

    # Music Tab
    url(r'^music/', include(patterns(view_location,
        url(r'^$',
            'music',
            name='music'),
        # Forms
        url(r'^album/add/$',
            'AddEditAlbum',
            name='albumForm'),
        url(r'^album/(?P<albumID>[\.\w-]+)/edit/$',
            'AddEditAlbum',
            name='editAlbumForm'),
        url(r'^album/(?P<albumID>[\.\w-]+)/tracks/add/$',
            'AddEditTracks',
            name='tracksForm'),
        #url(r'^interview/add/$',
        #    'interview_form',
        #    name='interview_form'),
        #url(r'^interview/add/(?P<trackID>[\.\w-]+)$',
        #    'interview_form',
        #    name='interview_form'),
    ))),
    # Video Tab
    url(r'^videos/', include(patterns(view_location,
        url(r'^$',
            'videos',
            name='videos'),
        # Forms
        url(r'^album/add/$',
            'AddEditAlbum',
            {'success_url': 'musician:video_tracks_form'},
            name='video_album_form'),
        url(r'^album/(?P<albumID>[\.\w-]+)/edit/$',
            'AddEditAlbum',
            {'success_url': 'musician:video_tracks_form'},
            name='video_edit_album'),
        url(r'^album/(?P<albumID>[\.\w-]+)/tracks/add/$',
            'add_video_to_album',
            name='video_tracks_form'),
        #url(r'^interview-video/add/$',
        #    'interview_video_form',
        #    name='interview_video_form'),
        #url(r'^interview-video/add/(?P<trackID>[\.\w-]+)$',
        #    'interview_video_form',
        #    name='interview_video_form'),
    ))),

)
